language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

compiler:
  - gcc

#script: cmake . && make && (cd bin && ./tests)
script:  cmake -S . -B build && make -C build && make -C build test